### ISSUE TITLE
Put vaultenv on hackage

### ISSUE THREAD

**Issue by arianvp** [channable/vaultenv#1]

**Comment by rightfold** [comment]
With Travis you can automatically upload binaries to GitHub with not too much effort

**Comment by duijf** [comment]
> What we could do is provide a binary distrubtion when we tag releases though... this is possible through Github

The current release process is to put binaries on the GH releases page, so I think this can be closed.

If anyone sees this and has requests wrt to the release process, please open a new ticket :)
