### ISSUE TITLE
Increase upperbound on haskell tls package

### ISSUE THREAD

**Issue by PierreR** [channable/vaultenv#142]
Vaultenv is currently marked as `broken` in nixpkgs (24.05) because of the haskell dependency constraint : tls >=1.4 && <1.7

Would it be possible to release a new version that supports tls 1.8, the current latest version used in nixpkgs 24.05 ?

Thanks

**Comment by alex-mckenna** [comment]
@PierreR I just released [v0.17.0](https://github.com/channable/vaultenv/releases/tag/v0.17.0) which uses `tls-1.8.0` when I build it in the nix environment of this repository.
