### ISSUE TITLE
Read vault config from environment?

### ISSUE THREAD

**Issue by arianvp** [channable/vaultenv#28]
I don't want to respecify `--host` in every service we have.  Just have some global `EnvironmentFile` that sets the setting.

**Comment by Tasqa** [comment]
or even better, put consul to good use? See: https://github.com/hashicorp/consul-template
We would only have to seed it with a vault token in the `EnvironmentFile`  and we could even monitor for CONFIG changes with restarts...

**Comment by arianvp** [comment]
Vault and Consul are not necessarily used in conjunction. I'd like to keep this tool generic in that sense.   If we want  to have consul integration, then we can use already existing approaches that give the same features as vaultenv + more. Namely Consul-template or confd.

**Comment by duijf** [comment]
I don't really understand how this pertains to `vaultenv` itself. You will still need a mechanism to get the `EnvironmentFile` on every host you want to have the same config on.

We could make things a bit easier. Some options (not mutually exclusive):

 - Respect `VAULT_ADDR` when set.
 - Introduce `VAULT_HOST` and do DNS SRV record lookups to get the port, then fall back to the default Vault port. (We probably also want to introduce `VAULT_PORT` for symmetry)

Thoughts?

**Comment by rkrzr** [comment]
I think we should keep this simple:

Respect either `VAULT_ADDR` or `VAULT_HOST` and `VAULT_PORT` when set.
Command-line flags should take priority over env variables when set.

This way we can set these env vars in the `EnvironmentFile` everywher and don't have to build new packages when something with vault changes.

**Comment by duijf** [comment]
Context for non-Channablers reading along: internally, we use the systemd services, which have an `EnvironmentFile` directive where you can specify a file with environment variables to make available to the current process.

This discussion is about how we can make vaultenv work nicely with this, by introducing environment variables for configuration.

**Comment by duijf** [comment]
I've started with this on the [`config-from-env`](https://github.com/channable/vaultenv/tree/config-from-env) branch. I've almost got things working, except I'm having trouble with the CLI flags, such as `--no-connect-tls`
