### ISSUE TITLE
put vaultenv in env

### ISSUE THREAD

**Issue by degilq** [channable/vaultenv#36]
i try run 

exec -- vaultenv \
  --no-connect-tls \
  --token ${VAULT_TOKEN_LOCAL} \
  --host ${VAULT_HOST} \
  --secrets-file /tmp/secretos \
  /usr/bin/env

but i dont see env in container pod

**Comment by rkrzr** [comment]
You don't need to call `exec` yourself, `vaultenv` will do that for you (after putting all the requested secrets into the environment). Try calling just:

```
vaultenv
--no-connect-tls
--token ${VAULT_TOKEN_LOCAL}
--host ${VAULT_HOST}
--secrets-file /tmp/secretos
/usr/bin/env
```

This should then print all the secrets that you put into the `/tmp/secretos` file.

**Comment by ruuda** [comment]
Is the `exec` part of a dockerfile @degilq? What are you trying to achieve?

**Comment by degilq** [comment]
yes , i try do a vaultenv export

2018-02-13 15:47 GMT-03:00 Ruud van Asseldonk <notifications@github.com>:

**Comment by arianvp** [comment]
Could you share your  kubernetes pod template, and/or dockerfile here?

**Comment by duijf** [comment]
Hey @degilq, friendly reminder on this ticket! We'd love to help :smile: 

Could you post your entire Dockerfile (or a minimal example that shows the issue you're having), plus the commands you're using to launch your container?

If you try to run `vaultenv` from Docker, you need to invoke it with every `RUN` or `CMD` step that needs access to secrets

**Comment by rkrzr** [comment]
I'll close this one due to inactivity. Feel free to reopen.

**Comment by raiknet** [comment]
I would like to re-open this issue since I have also problems with forking and the correct command. This works in my docker container:  `vaultenv env` but not vaultenv  echo $TEST

**Comment by duijf** [comment]
@raiknet are you trying to execute this in your shell?

```
$ vaultenv echo $TEST
```

The `$TEST` variable lookup will be executed by your shell before launching vaultenv. Since the var is not set, vaultenv will be launched with arguments `['vaultenv', 'echo']` (and not `['vaultenv', 'echo', '$TEST']`) which prints an empty string.

You can confirm this by using the `env` command to set `TEST` and then running echo. This will also print an empty string:

```
$ env echo $TEST
```

You're probably looking for something like this:

```
$ vaultenv -- bash -c 'echo $TEST'

# Equivalent `env` invocation
$ env TEST=foo bash -c 'echo $TEST'
```

**Comment by raiknet** [comment]
Thank you this makes sense  and removed my blocker, but I still have to do some testing.

**Comment by raiknet** [comment]
Thank you again, this worked.
