### ISSUE TITLE
Doesn't work if secrets file has a line feed at the end

### ISSUE THREAD

**Issue by mesaugat** [channable/vaultenv#50]
My secrets file has a line feed at the end, and looks like `vaultenv` is trying to parse that too.

```
DB_HOST=path#DB_HOST
DB_NAME=path#DB_NAME

```

`vaultenv` should ignore new lines and whitespaces in the secrets file.

This won't work as well.

```
DB_HOST=path#DB_HOST

DB_NAME=path#DB_NAME
```

This is what `vaultenv` says:
```
[ERROR] File Secret path '' does not contain '#' separator. could not be parsed
```

**Comment by mesaugat** [comment]
I think this fixes https://github.com/channable/vaultenv/pull/47 this issue?

**Comment by duijf** [comment]
Thanks for the report!

The previous parser was indeed strict about this. The new parser has more lenient whitespace handling. Making a release with the new parser as we speak :)

**Comment by duijf** [comment]
New release is ready: https://github.com/channable/vaultenv/releases/tag/v0.8.0

Closing this ticket, but feel free to reopen/create another if you have any issues

**Comment by mesaugat** [comment]
@duijf Awesome, great thanks! 💯 🥇
