### ISSUE TITLE
vaultenv --version

### ISSUE THREAD

**Issue by mesaugat** [channable/vaultenv#52]
Not absolutely required but most `unix` commands have a `--version` to get the version of the command.

Another option would be to show the version number in the help output.

```bash
$ vault --help

vaultenv 0.8.0 - run programs with secrets from HashiCorp Vault

Usage: vaultenv [--host HOST] [--port PORT] [--token TOKEN]
                --secrets-file FILENAME CMD [ARGS...] ([--no-connect-tls] |
                [--connect-tls]) ([--no-validate-certs] | [--validate-certs])
                ([--no-inherit-env] | [--inherit-env])
                [--retry-base-delay-milliseconds MILLISECONDS]
                [--retry-attempts NUM] [--log-level error | info]

...
```

**Comment by duijf** [comment]
Reasonable request. Should be straightforward. PR is welcome as well if you'd like :)

**Comment by mesaugat** [comment]
I've barely done any Haskell. I will have to learn and comeback.

**Comment by duijf** [comment]
The new version includes this :) https://github.com/channable/vaultenv/commit/9f9367290a37e3bdb427942dc8e969f2687f4dcc
