### ISSUE TITLE
Parse secrets version 2 data

### ISSUE THREAD

**Issue by hhallman** [channable/vaultenv#62]
I can't seem to get vaultenv to work with key-value secrets engine version 2. vaultenv terminates with error 
> [ERROR] Key KEY not found for path PATH

Inspecting Vault's response for version 1 and version 2, it seems likely that the additional 'data' object is causing the problem.

It seems that secrets on vault's key-value/secret engine format 2 is not parsed correctly. (Or documentation is lacking, so I can't understand how to write the secrets file)

In version 2, data is wrapped as such response.data.data.usernmame, here's an actual example from my audit log:

```
    "response": {
        "data": {
            "data": {
                "password": "hmac-sha256:35765f6bd7eb2658b8681e5359c67e5750f13f4f91ecd59210b6dd48a5171dae",
                "username": "hmac-sha256:10f7d662d7052b68c77549181bfa20ee2f26b60d67dd445cad773e23f82fde8d"
            },
            "metadata": {
                "created_time": "hmac-sha256:e37df48fdde45f74021285c9ae71b00dfb367fcf4b93b3bdbd574e9aa20c50a9",
                "deletion_time": "hmac-sha256:32d8ee3d91fe8a45514f70d2d9d0b0d139a494da8dd87ca9405e28d78713acd6",
                "destroyed": false,
                "version": 1
            }
        }
    },
```

vaultenv gives me error-response: 
[ERROR] Key username not found for path data/X/X

my config is
```
VERSION 2

MOUNT prod
report_connection_user=data/X/X#username
```

**Comment by duijf** [comment]
Hi @hhallman, thanks for getting in touch!

> It seems that secrets on vault's key-value/secret engine format 2 is not parsed correctly. (Or documentation is lacking, so I can't understand how to write the secrets file)

Yes, it is correct that this hasn't been implemented yet. I wasn't aware that the response format changed in version 2. Thank you for taking the time to make a detailed report :)

So it seems that `vaultenv` needs to be aware of the type of secret engine mounted at a path. We could go one of the following ways.

 - Make the user explicitly set the type of an engine in the config file.
 - Make `vaultenv` request this information from Vault ([through `/sys/mounts`](https://www.vaultproject.io/api/system/mounts.html)) and act based on that.

**Explicit**

```
+ Does not require another API call
~ Potentially less user friendly (up for debate)
- Can go out of sync with reality
- Requires changing the secret file format
```

**Implicit**

```
+ User friendly (up for debate)
- Not forwards compatible with secret engines with a format which corresponds to one that's already implemented
- Requires more permissions on the Vault token (probably)
- Potentially backwards incompatible (because of the former)
```

**Comment by rkrzr** [comment]
> Personally, I'm leaning towards changing the config file (in a backwards compatible way) and making the user able to specify this explicitly. 

I'm also strongly in favor of making this explicit in the config file. Less magic is generally better, and additionally it also serves as a form of documentation to state what type of secret engine is expected. If the type should suddenly change, I would want to get an error, since that would be unexpected behavior.

**Comment by hhallman** [comment]
Thank you for your answer! Highly appreciated.
I would like to throw in a question that might be relevant in making the best solution: (I would research a bit to give the best answer, but feel that quick response is best.)
How about reading information from other secret engines, like database? I suppose the best solution would allow that as well. (If not already supported).
From a user's perspective, I would think that it should be possible to detect the format of the response in a safe way. Perhaps by checking, 

- is there a response.data.data?
- is there a response.data.metadata?
- does the key exist under response.data.data?

I think it would be very convenient if the format can be auto-detected, for e.g. the case when an admin wants to upgrade the secrets engine and re-use paths if the already deployed services could just keep working with no changes.
(In my case, I ran into this when deploying code from test to production, because it seems that Vault promotes v2 in dev-mode but v1 in production mode, but I have to check this. At least, somehow this is how it ended up for me.)

**Comment by duijf** [comment]
Thanks for weighing in!

> How about reading information from other secret engines, like database? I
> suppose the best solution would allow that as well. (If not already
> supported).

The database engine can be used with `vaultenv`:

```
VERSION 2

MOUNT database
creds/<yourcustomrole>
```

is translated into a `GET /v1/database/creds/<yourcustomrole>`. This [endpoint](https://www.vaultproject.io/api/secret/databases/index.html#generate-credentials)
gives a response of the form:

```json
{
  "data": {
    "username": "root-1430158508-126",
    "password": "132ae3ef-5a64-7499-351e-bfe59f3a2a21"
  }
}
```

which vaultenv can work with.

However, this does not apply to all secret engines. Some have a different
response format (or even API). For example:

  - The PKI engine requires a POST method for it's most useful functionality
    ([generating certs](https://www.vaultproject.io/api/secret/pki/index.html#generate-certificate)).
  - The same goes for the SSH engine ([docs](https://www.vaultproject.io/api/secret/ssh/index.html#generate-ssh-credentials))

If we're ever going to support those endpoints, it would be nice if the
type of the secret engine was explicit in the config file.

For both simplicity of the implementation, and for transparency to the
user, I would like to make this explicit to some degree. The odds that
your secret file can just be used without changes when changing from one
secret engine to another seems quite small.

> I think it would be very convenient if the format can be auto-detected,
> for e.g. the case when an admin wants to upgrade the secrets engine and
> re-use paths if the already deployed services could just keep working
> with no changes.

However for the K/V engine I can definitely see the value of supporting both V1
and V2 of the secret engine. Especially as the semantics of the API look like
they are the same. Without this, it wouldn't really be possible to migrate a
production instance of Vault to the new KV engine version without copying all
the secrets into a new KV engine mount.

In general, I like explicit tools. We should probably include some sort of type
in the `MOUNT` to allow us to support things like the PKI or SSH engine, but
I'm not too sure what the best way forward is.

 - Should we include the type of secrets engine? That would lead to redundant
   keywords: the database and the KV1 secret engines seem to function
   identially. We'd also have to decide on a per-engine basis what would be the
   blessed API call: e.g. for the PKI engine, would it be "create new cert"
   or "read cert metadata"?
 - Should we try to find some commonality between secret engines/mounts? Like
   specify what HTTP verbs should be used?

Maybe both? Like `MOUNT <path> <type> <verb>`?

**Comment by duijf** [comment]
@hhallman FYI, I've started working on this: https://github.com/channable/vaultenv/pull/65

**Comment by duijf** [comment]
This one has been implemented, cutting a new release now
