### ISSUE TITLE
Support VAULT_ADDR

### ISSUE THREAD

**Issue by denibertovic** [channable/vaultenv#66]
Most vault tools seem to support a standardized set of environment variables. More specifically the vault cli checks for VAULT_ADDR rather than 2 separate variables VAULT_HOST and VAUL_PORT. It would be great if vualtenv followed the same convention.

**Comment by duijf** [comment]
Hi @denibertovic! Thanks for the suggestion

I like this idea, but I'm slightly worried about introducing breaking changes here. Ideally, we make a vaultenv release which supports both `VAULT_(HOST|PORT)` and `VAULT_ADDR` at the same time. 

There would need to be some precedence / warnings about these settings in case both are present at teh same time. Do you have any opinions on this?

**Comment by denibertovic** [comment]
Hi @duijf I like this idea. Supporting both schemes is probably best and then possibly deprecating the VAULT_(HOST|PORT) scheme after some time. 

IMO VAULT_ADDR should take precedence over VAULT_(HOST|PORT). But if it's not defined then VAULT_(HOST|PORT) should be used while logging a deprecation warning.

**Comment by orinokai** [comment]
I've just run into this one too. I have a build pipeline that needs to pass VAULT_ADDR to Terraform. After that, I have to use string manipulation to break the var apart into VAULT_HOST and VAULT_PORT before passing those vars to my servers in a vaultenv.conf file. It's not a massive problem, but if vaultenv supported VAULT_ADDR it would be very pleasing 👌to clean up my build files. I had a look at the code in case I could help, but Haskell is beyond me.

**Comment by duijf** [comment]
> I had a look at the code in case I could help, but Haskell is beyond me.

No worries. If someone else wants to have a go; we'd take PRs implementing this.

**N.B.** Vault itself also accepts the scheme in `VAULT_ADDR` [also accepts](https://www.vaultproject.io/docs/commands/#vault_addr); not just the host and port. Vaultenv should probably do the same thing
