### ISSUE TITLE
vaultenv parsing ARGS for CMD as options for vaultenv

### ISSUE THREAD

**Issue by alexhumphreys** [channable/vaultenv#70]
When I run `vaultenv env`, I get the environment with the extra values from vault as expected. However when I run 'vaultenv env --null` I get the following error:
```
Invalid option `--null'

Usage: vaultenv [--version] [--host HOST] [--port PORT] [--token TOKEN]
                [--secrets-file FILENAME] CMD [ARGS...] ([--no-connect-tls] |
                [--connect-tls]) ([--no-validate-certs] | [--validate-certs])
                ([--no-inherit-env] | [--inherit-env])
                [--retry-base-delay-milliseconds MILLISECONDS]
                [--retry-attempts NUM] [--log-level error | info] [--use-path]
```

So it looks like `vaultenv` is trying to parse `--null` as it's own option, rather than passing it to `env`. Running `env --null` works as expected.

As for my setup, I built vaultenv from source from master, and the output of `vaultenv --version` is `0.10.0`. I'm on Ubuntu 16.04.6 LTS. The following options were passed to vaultenv via the `.env` file:

```
VAULT_HOST=redacted.example.com
VAULT_PORT=80
VAULTENV_CONNECT_TLS=false
VAULTENV_SECRETS_FILE=.vault.secrets
VAULT_TOKEN=s.redacted
```

I'm new to vaultenv so maybe I'm doing something basic wrong. Any help would be appreciated.

**Comment by duijf** [comment]
You should be able to use `--` between options for `vaultenv` and options for the command you're calling. So in this instance, you can `vaultenv -- env --null

**Comment by alexhumphreys** [comment]
Ah cool that did it, thanks for the fast response :)
